### ISSUE TITLE
Add child properties for gtk::Notebook

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gtk#495]
Hello.
I would like to add the child properties for `gtk::Notebook`:
I tried the following:
```toml
    [[object.child_prop]]
    name = "detachable"
    type = "gboolean"
    [[object.child_prop]]
    name = "menu-label"
    type = "gchar*"
    [[object.child_prop]]
    name = "position"
    type = "gint"
    [[object.child_prop]]
    name = "reorderable"
    type = "gboolean"
    [[object.child_prop]]
    name = "tab-expand"
    type = "gboolean"
    [[object.child_prop]]
    name = "tab-fill"
    type = "gboolean"
    [[object.child_prop]]
    name = "tab-label"
    type = "gchar*"
```
However, it does not for the `gchar*` type since I get the following error:
```
ERROR:gir::analysis::child_properties: Bad type `gchar*` of child property `menu-label` for `Notebook`
ERROR:gir::analysis::child_properties: Bad type `gchar*` of child property `tab-label` for `Notebook`
```

It is for the same reason I added the child properties for `gtk::Box`: it is to ease the use in my `relm` crate.

Thanks to add these properties.
