### ISSUE TITLE
Pass features to `docs.rs` doc generation

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk#574]
It's apparently possible to pass features when `docs.rs` is building crates:

```toml
[package.metadata.docs.rs]
features = ["serde-1", "quickcheck"]
```

Talk about a hidden feature...
