### ISSUE TITLE
Cross Compilation issues

### ISSUE THREAD

**Issue by gbip** [gtk-rs/gtk#600]
The [instructions](http://gtk-rs.org/tuto/cross) on your website are really great, but since the packages mentionned are only available on AUR it is pretty hard to replicate the build process on any other distribution.
Here is where I am :
1. I downloaded precompiled binaries (only gtk-10 is available) from [here](http://win32builder.gnome.org/). I went for the 64 bits version.
2. I uncompressed the archive in `/opt/gtkwin`, and gave myself all rights to this folder.
3. I executed `find -name '*.pc' | while read pc; do sed -e "s@^prefix=.*@prefix=$PWD@" -i "$pc"; done
` while being in `/opt/gtkwin`. It is said to prepared the files to their folder (cf this [AskUbuntu thread](https://askubuntu.com/questions/942010/how-to-compile-c-gtk3-program-in-ubuntu-for-windows#942179)).
4. I added a `.cargo/config` in my project with the following content :
```toml
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
rustflags = ["-L /opt/gtkwin/lib"]
```
5. I created `build_windows.sh` that contains :  
```bash
#!/bin/bash
export PKG_CONFIG_ALLOW_CROSS=1
export PKG_CONFIG_PATH=/opt/gtkwin/lib/pkgconfig
cargo build --target=x86_64-pc-windows-gnu
```
6. I think that at somepoint I restarted my computer which solved some issues with the linker not finding `-lgtk-3`.

Now even if it looks fine, there is still an undefined reference. Here is the error :
`/gtk-0.3.0/src/auto/enums.rs:513: undefined reference to 'gtk_button_role_get_type'`

My Cargo.toml contains the following :
```toml
[dependencies.gtk]
version = "0.3.0"
features = ["v3_10"]
```
I think that this is a version clonfict, but since the precompiled binaries where clearly built on gtk-3.10, I have no idea where is the problem.

Can one of you take a quick look ? I don't have a huge experience with linkers and cross-compilation.

I would be glad to complete the tutorial once it works. :smile:
