### ISSUE TITLE
set_icon_name exists, but is not accessible

### ISSUE THREAD

**Issue by starfear** [gtk-rs/gtk#855]
I have included all traits, using
```rust
use gio::prelude::*;
use gtk::prelude::*;
```
but code below is not working:
```rust
let button = gtk::Button::new();
button.set_icon_name("mail-reply-sender");
```

I have also tried:
```rust
use gtk::*;
use gtk::ToolButtonExt;
use ToolButtonExt;
```

Error: ** the method `set_icon_name` exists but the following trait bounds were not satisfied:
           `gtk::Button : gtk::GtkWindowExt`
           `gtk::Button : gtk::ToolButtonExt`
**

my cargo config:
```toml
[dependencies.gtk]
version = "0.7.0"
# features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]

```
