### ISSUE TITLE
Buttons aren't getting colored

### ISSUE THREAD

**Issue by MGlolenstine** [gtk-rs/gtk#976]
My buttons are loaded and my styling does get applied, as other CSS fields do get set, but buttons don't.

My CSS 

```CSS

label{
    font-size: 48px;
}

box {
    background-color: #888888;
}

button:active {
    background-color: #000;
}

button:hover {
    background-color: #000;
}
```
